version: '3.8'

services:    
  postgres:
    image: postgres:15
    container_name: api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pbl409_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: cahce-storage
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - cache
volumes:
  postgres_data:
