version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: library-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pbl409_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: