version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: library-postgres
    ports:
      - "5432:5432"
    environment:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: